workflows:
  ios-workflow:
    name: Keyboard Extension Build
    environment:
      xcode: latest
      vars:
        XCODE_PROJECT: "TactileLearnerKeyboard.xcodeproj"
        XCODE_SCHEME: "KeyboardExtension"
    scripts:
      - name: Setup Project Structure
        script: |
          mkdir -p TactileLearnerKeyboard.xcodeproj
          mkdir -p TactileLearnerKeyboard
          mkdir -p KeyboardExtension
          
          # Create minimal Xcode project
          echo "// !$*UTF8*$!" > TactileLearnerKeyboard.xcodeproj/project.pbxproj
          echo '{}' > TactileLearnerKeyboard.xcodeproj/project.xcworkspace/contents.xcworkspacedata
          
          # Move source files
          mv KeyboardViewController.swift KeyboardExtension/
          mv KeyboardExtension-Info.plist KeyboardExtension/Info.plist
          mv TactileLearnerKeyboard-Info.plist TactileLearnerKeyboard/Info.plist

      - name: Build Extension
        script: |
          xcodebuild build \
            -scheme "$XCODE_SCHEME" \
            -project "$XCODE_PROJECT" \
            -configuration Debug \
            CODE_SIGNING_ALLOWED="NO"
    artifacts:
      - KeyboardExtension/**/*.swift
      - KeyboardExtension/**/*.plist
