workflows:
  ios-keyboard:
    name: Keyboard Build
    environment:
      xcode: latest
    triggering:
      branch_patterns:
        - pattern: main
          include: true
          build_on: every_commit
    scripts:
      - name: Build Keyboard Extension
        script: |
          # Navigate to KeyboardExtension directory
          cd KeyboardExtension
          
          # Build without signing
          xcodebuild build \
            -scheme "KeyboardExtension" \
            -configuration Debug \
            CODE_SIGNING_ALLOWED="NO"
          
          # Generate unsigned .ipa for testing
          mkdir -p Payload
          mv Build/Products/Debug-iphoneos/KeyboardExtension.appex Payload/
          zip -r Keyboard.ipa Payload
    artifacts:
      - KeyboardExtension/Keyboard.ipa
