workflows:
  ios-keyboard:
    name: Keyboard Build
    environment:
      xcode: latest
    triggering:
      events:
        - push
      branch_patterns:
        - pattern: main
          include: true
    scripts:
      - name: Build Keyboard Extension
        script: |
          cd KeyboardExtension
          
          # Build the extension
          xcodebuild build \
            -scheme "KeyboardExtension" \
            -configuration Debug \
            CODE_SIGNING_ALLOWED="NO"
          
          # Generate unsigned .ipa
          mkdir -p Payload
          mv Build/Products/Debug-iphoneos/KeyboardExtension.appex Payload/
          zip -r Keyboard.ipa Payload
    artifacts:
      - KeyboardExtension/Keyboard.ipa
